In [ ]:
#sort()
A=[1,2,5,21,4,7]
A.sort()
print(A)

[1, 2, 4, 5, 7, 21]


In [ ]:
#sorted()
a=[7,4,9,2,4]
b=sorted(a)
print(a)
print(b)

[7, 4, 9, 2, 4]
[2, 4, 4, 7, 9]


In [ ]:
import numpy as np

In [ ]:
#reshape: convert into 2d array
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#linspace(1st number,last number,b/w no.of elements)
a=np.linspace(10,11,12).reshape(3,4)
print(a)

[[10.         10.09090909 10.18181818 10.27272727]
 [10.36363636 10.45454545 10.54545455 10.63636364]
 [10.72727273 10.81818182 10.90909091 11.        ]]


In [ ]:
#reshape(groups,rows,cols):changes need saving in another array
a=np.array([34,56,73,23,54,75,34,43]).reshape(2,2,2)
print(a)

[[[34 56]
  [73 23]]

 [[54 75]
  [34 43]]]


In [ ]:
#resize:changes the shape of original array
b=np.array([34,56,73,23,54,75,34,43])
b.resize(2,2,2)
print(b)

[[[34 56]
  [73 23]]

 [[54 75]
  [34 43]]]


In [ ]:
#array creation and substraction
a=np.array([34,56,73,23])#array creation
b=np.array([3,5,4,8])
c=a-b
print(c)

[31 51 69 15]


In [ ]:
#array addition. here no concatinationlike list
a=np.array([34,56,73,23])#array creation
b=np.array([3,5,4,8])
c=a+b
print(c)

[37 61 77 31]


In [ ]:
# one-on-one multiplication
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("---------------------------")
c=a*b
print(c)

[[34 56]
 [73 23]]
--------------------------
[[3 5]
 [4 8]]
---------------------------
[[102 280]
 [292 184]]


In [1]:
#matrix mutiplication
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("---------------------------")
c=a@b
print(c)

NameError: name 'np' is not defined

In [ ]:
#matrix mutiplication
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("---------------------------")
c=a.dot(b)
print(c)

[[34 56]
 [73 23]]
--------------------------
[[3 5]
 [4 8]]
---------------------------
[[326 618]
 [311 549]]


In [ ]:
#max and min of array
a=np.array([34,56,73,23])
print(a.max())
print(a.min())

73
23


In [ ]:
#max using axis=0,1
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(a.max(axis=0))#column wise big num
print("--------------------------")
print(a.max(axis=1))#row wise big num

[[34 56]
 [73 23]]
--------------------------
[73 56]
--------------------------
[56 73]


In [ ]:
#min using axis=0,1
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(a.min(axis=0))#column wise small num
print("--------------------------")
print(a.min(axis=1))#row wise small num

[[34 56]
 [73 23]]
--------------------------
[34 23]
--------------------------
[34 23]


In [ ]:
#joining arraays: stack
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("--------------------------")
print("after vertically staking arrays!")#v.stack:vertically
print(np.vstack((a,b)))

[[34 56]
 [73 23]]
--------------------------
[[3 5]
 [4 8]]
--------------------------
after vertically staking arrays!
[[34 56]
 [73 23]
 [ 3  5]
 [ 4  8]]


In [ ]:
#joining arraays: stack
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("--------------------------")
print("after horizontally staking arrays!")#h.stack:horizontally
print(np.hstack((a,b)))

[[34 56]
 [73 23]]
--------------------------
[[3 5]
 [4 8]]
--------------------------
after horizontally staking arrays!
[[34 56  3  5]
 [73 23  4  8]]


In [ ]:
#joining arraays: stack
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("--------------------------")
#np.stack: 3d array axis=0
print(np.stack((a,b),axis=0))

[[34 56]
 [73 23]]
--------------------------
[[3 5]
 [4 8]]
--------------------------
after vertically staking arrays!
[[[34 56]
  [73 23]]

 [[ 3  5]
  [ 4  8]]]


In [ ]:
#joining arraays: stack
a=np.array([34,56,73,23]).reshape(2,2)
b=np.array([3,5,4,8]).reshape(2,2)
print(a)
print("--------------------------")
print(b)
print("--------------------------")
#np.stack: 3d array axis=1
print(np.stack((a,b),axis=1))

[[34 56]
 [73 23]]
--------------------------
[[3 5]
 [4 8]]
--------------------------
[[[34 56]
  [ 3  5]]

 [[73 23]
  [ 4  8]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("after dstack")#no.of rows=no.of groups
print(np.dstack(a))#no.of col in every group=no.of rows in every grpup

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting:")
np.vsplit(a,(2,5))#(before col2 and before col5 and rest)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting:


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting:")
print(np.vsplit(a,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting:
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print("after splitting:")
np.vsplit(a,(2,3))#(before col2 and col2  seperate before col3 and 3 sep)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting:


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays!
a=np.arange(18).reshape(3,6)
print(a)
print("after splitting:")
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting:
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [ ]:
#splitting arrays!
a=np.arange(18).reshape(3,6)
print(a)
print("after splitting:")
np.hsplit(a,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting:


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
a=np.array([12,3,21,43,45,4,65,77,6,9]).reshape(2,5)
print(a)
print(a.argmax())#index of highest number


[[12  3 21 43 45]
 [ 4 65 77  6  9]]
7


In [ ]:
a=np.array([12,3,21,43,45,4,65,77,6,9]).reshape(2,5)
print(a)
print(a.argmax(axis=0))#index of max number col wise
#axis 0:
# 0 0 0 0 0
#1 1 1 1 1
#2 2 2 2 2

[[12  3 21 43 45]
 [ 4 65 77  6  9]]
[0 1 1 0 0]


In [ ]:
a=np.array([12,3,21,43,45,4,65,77,6,9]).reshape(2,5)
print(a)
print(a.argmax(axis=1))#index of max number row wise
#axis=1
#0 1 2 3
#0 1 2 3
#0 1 2 3


[[12  3 21 43 45]
 [ 4 65 77  6  9]]
[4 2]


In [ ]:
a=np.array([12,3,21,43,45,4,65,77,6,9]).reshape(2,5)
print(a)
print(a.argmin(axis=0))#index of max number col wise
#axis 0:
# 0 0 0 0 0
#1 1 1 1 1
#2 2 2 2 2

[[12  3 21 43 45]
 [ 4 65 77  6  9]]
[1 0 0 1 1]


In [ ]:
a=np.array([12,3,21,43,45,4,65,77,6,9]).reshape(2,5)
print(a)
print(a.argmin(axis=1))#index of max number row wise
#axis=1
#0 1 2 3
#0 1 2 3
#0 1 2 3

[[12  3 21 43 45]
 [ 4 65 77  6  9]]
[1 0]


In [ ]:
#statistics formulaes
#mean,median,std,var
a=np.array([3,5,7,9,21])
print("mean: ",np.mean(a))
print("median: ",np.median(a))
print("variance: ",np.var(a))
print("standard dev: ",np.std(a))

mean:  9.0
median:  7.0
variance:  40.0
standard dev:  6.324555320336759


In [ ]:
#trignometry
a=np.pi
print(a)#radians
np.rad2deg(a)#radians to degree

3.141592653589793


180.0

In [ ]:
#array of radians to degree
a=np.array([np.pi/4, np.pi/3, np.pi/2, np.pi])
print(a)
print(np.rad2deg(a))

[0.78539816 1.04719755 1.57079633 3.14159265]
[ 45.  60.  90. 180.]


In [ ]:
#degree to radians
a=np.array([30,45,60,90,120,180])
d=np.deg2rad(a)
print(d)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
#sin values
a=np.array([30,45,60,90,120,180])
np.sin(a)

array([-0.98803162,  0.85090352, -0.30481062,  0.89399666,  0.58061118,
       -0.80115264])

In [ ]:
#cos values
a=np.array([30,45,60,90,120,180])
np.cos(a)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362,  0.81418097,
       -0.59846007])

In [ ]:
#tan values
a=np.array([30,45,60,90,120,180])
np.tan(a)

array([-6.4053312 ,  1.61977519,  0.32004039, -1.99520041,  0.71312301,
        1.33869021])

In [ ]:
#sin ^ -1
np.arcsin(1)

1.5707963267948966

In [ ]:
#cos ^ -1
np.arccos(1)

0.0

In [ ]:
#tan ^ -1
np.arctan(1)

0.7853981633974483

In [ ]:
#hypoteneuse
a=12
b=42
print(np.hypot(a,b))

43.68065933568311


In [ ]:
#searchig
a=np.array([30,45,60,90,120,180])
print(np.where(a==120))

(array([4]),)


In [ ]:
#searchig
a=np.array([30,45,60,90,120,180,120])
print(np.where(a==120))

(array([4, 6]),)


In [ ]:
#searchig for condition
a=np.array([30,45,60,95,120,187])
print(np.where(a%2==0))#print even

(array([0, 2, 4]),)


In [ ]:
#search sorted: sort the elements and return index
import numpy as np
N=np.array([45,78,3,12,6,5])
print(N)
print(np.searchsorted(N,12))

[45 78  3 12  6  5]
0


In [ ]:
import numpy as np
a=np.array([45,78,3,12,6,5])
print(a)
b=np.array([3,6,2,4,7,9])
print(b)
print(np.subtract(a,b))

[45 78  3 12  6  5]
[3 6 2 4 7 9]
[42 72  1  8 -1 -4]


In [ ]:
import numpy as np
a=np.array([45,78,3,12,6,5])
print(a)
b=np.array([3,6,2,4,7,9])
print(b)
print(np.divide(a,b))

[45 78  3 12  6  5]
[3 6 2 4 7 9]
[15.         13.          1.5         3.          0.85714286  0.55555556]


In [ ]:
#operations of array on 2operands
import numpy as np
a=np.array([45,78,3,12,6,5])
print(a)
b=np.array([3,6,2,4,7,9])
print(b)
print(np.divide(a,b))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.mod(a,b))
print(np.diff(a))
print(np.divmod(a,b))
print(np.sort(a))

[45 78  3 12  6  5]
[3 6 2 4 7 9]
[15.         13.          1.5         3.          0.85714286  0.55555556]
[48 84  5 16 13 14]
[42 72  1  8 -1 -4]
[0 0 1 0 6 5]
[ 33 -75   9  -6  -1]
(array([15, 13,  1,  3,  0,  0]), array([0, 0, 1, 0, 6, 5]))
[ 3  5  6 12 45 78]


In [ ]:
a=np.array([45,78,3,12,6,5])
print(a)
b=np.array([3,6,2,4,7,9])
print(b)


[45 78  3 12  6  5]
[3 6 2 4 7 9]


In [ ]:
#set operations
a=np.array([45,78,3,12,6,5])
b=np.array([3,6,2,4,7,9])
print("intersection",np.intersect1d(a,b))
print("setdiff",np.setdiff1d(a,b))

intersection [3 6]
setdiff [ 5 12 45 78]


In [ ]:
#round functions
a=np.fix([-1.888,2.456])#fix
b=np.around([-1.888,2.456])#around
c=np.trunc([-1.888,2.456])#truncate
d=np.floor([-1.888,2.456])#floor
e=np.ceil([-1.888,2.456])#ceil
print(a)
print(b)
print(c)
print(d)
print(e)


[-1.  2.]
[-2.  2.]
[-1.  2.]
[-2.  2.]
[-1.  3.]


In [ ]:
#cumulative sum: add the before elments
a=np.array([45,78,3,12,6,5])
print(a)
print(np.cumsum(a))
print(np.cumprod(a))#cumulative product

[45 78  3 12  6  5]
[ 45 123 126 138 144 149]
[     45    3510   10530  126360  758160 3790800]
12


In [ ]:
#find lcm,gcd
print(np.lcm(4,6))
print(np.gcd(4,6))

12
2


In [ ]:
#lcm,gcd for an array of elements
a=np.array([45,78,3,12,6,5])
print("lcm:",np.lcm.reduce(a))
print("gcd:",np.gcd.reduce(a))


lcm: 2340
gcd: 1


In [ ]:
#random module
from numpy import random as rd
a=rd.rand()#default limit 0to o.99
print(a)

0.02766184930267579


In [ ]:
a=rd.rand(10)#default limit 0to o.99 gereates 10 number
print(a)

[0.20623493 0.07966503 0.32122147 0.01576168 0.73809561 0.51481407
 0.87695184 0.37618562 0.4154241  0.52217796]


In [ ]:
a=rd.randint(50,size=6)#limit is 6
print(a)

[42 27 14  8 34 38]


In [ ]:
a=rd.randint(50,size=(2,3))#limit
print(a)

[[32 15 47]
 [25  0  6]]


In [ ]:
#inner joint
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.inner(a,b))#1*4+2*5+3*6

32


In [ ]:
#outer joint
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.outer(a,b))#1*(4,5,6) 2*(4,5,6) 3*(4,5,6)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.cross(a,b))#at 1st leave1st col and do mutiplication on next 1,2
# indexs and for 2nd it do 1st and 3rd col mul ...

[-3  6 -3]
