In [ ]:
#Variable
a=10
print("i am ",a,"years old")

i am  10 years old


In [ ]:
#arthemetic of 2 integer variables
a=int(input("enter 1st"))
b=int(input("enter 2nd"))
c=(a+b)
print ("add: ",c)
print("sub: ",a-b)
print("product: ",a*b)
print("division: ",a/b)
print("modules: ",a%b)
print("power: ",a**b)
print("floor div: ",a//b)

enter 1st36
enter 2nd6
add:  42
sub:  30
product:  216
division:  6.0
modules:  0
power:  2176782336
floor div:  6


In [ ]:
#newwlist=[(st of if) if (cond) else (st of else)for  ]
l1=[23,67,12,36,69]
res=[i*i if i>50 else 'x' for i in l1]
print(res)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#take a salary from the user if the salary is more than 50k there is a 10% tax print his final salary
a=float(input("enter salary: "))
if a>=50000:
  b=a*(10/100)
  print("salary is deducted 10%:",b)
  print("salary is: ",a-b)
else:
  print("no tax")

enter salary: 50000
salary is deducted 10%: 5000.0
salary is:  45000.0


In [1]:
#get the salary from the user if the salary is more than or = to 50k apply 10% tax deduction if the salary is <=50k apply 5% tax if the salary is>=70k apply 12% tax if your salary exeeds 1lakh print you are promoted to next level
a=float(input("enter salary: "))
if a>=50000 and a<=70000:
  b=a*(10/100)
  print("salary is: ",a-b)
elif a<50000:
  b=a*(5/100)
  print("salary is: ",a-b)
elif a>70000 and a<100000:
  b=a*(12/100)
  print("salary is: ",a-b)
elif a>=100000:
  print("you are promoted")



enter salary: 60000
salary is:  54000.0


In [ ]:
#range of number
n=int(input("enter n: "))
for i in range(0,n):
  print(i)

enter n: 6
0
1
2
3
4
5


In [ ]:
#table using range
n=int(input("enter n: "))
for i in range(1,11):
  print(n ,"*" ,i,"=" ,i*n)

enter n: 9
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90


In [ ]:
#table using while
n=int(input("enter n: "))
i=1
while (i<=10):
  print(n,"*",i,"=",i*n)
  i=i+1


enter n: 7
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70


In [ ]:
#create list in heterogenous
a=[12,3,"hi",'r']
for i in a:
 print (i)

12
3
hi
r


In [ ]:
#append
a=[12,3,"hi",'r']
a.append(1)
print(a)

[12, 3, 'hi', 'r', 1]


In [ ]:
#insert
a=[12,3,"hi",'r']
a.insert(1,"leela")
print(a)

[12, 'leela', 3, 'hi', 'r']


In [ ]:
#concatination of 2 lists
l2=[12,3,"hi",'r']
l1=['j',"hi",9]

print(l1+l2)

['j', 'hi', 9, 12, 3, 'hi', 'r']


In [ ]:
#pop and remove list elements
a=[12, 'leela', 3, 'hi', 'r']
a.pop(1)
print(a)
a.remove('hi')
print(a)

[12, 3, 'hi', 'r']
[12, 3, 'r']


In [ ]:
#extend to add 2 lists
a=[12, 'leela', 3, 'hi', 'r']
b=['j',8,'hello','p']
a.extend(b)
print(a)


[12, 'leela', 3, 'hi', 'r', 'j', 8, 'hello', 'p']


In [ ]:
#clear to empty full list
a=[12, 'leela', 3, 'hi', 'r']
a.clear()
print(a)

[]


In [ ]:
#create a list of random integers need 10 elements print there squares save the output in new list
l=[2,3,4,5,6]
l2=[]
for i in l:
  l2.append(i**2)
print(l2)

[4, 9, 16, 25, 36]


In [ ]:
#comprehension
l=[2,3,4,5,6]
res=[i*i for i in l]
print(res)

[4, 9, 16, 25, 36]


In [ ]:
#take the salary from user if salary<50k  10% tax otherwise 15% tax
a=float(input("enter the salary: "))
l=[ a-(a*(10/100)) if(a<=50000) else a-(a*(15/100)) ]
print(l)

enter the salary: 70000
[59500.0]


In [ ]:
#take the salary from user if salary<50k  10% tax otherwise 15% tax
l=[30000,60000]
l1=[(i-i*(10/100)) if i<=50000 else (i-i*(15/100)) for i in l]
print(l1)

[27000.0, 51000.0]


In [ ]:
#dictionary
a={"mentor":"jwalitha",1:"uma",2:"anu",3:"rohini"}
print(a)
print(a.keys())
print(a.values())
print(a[1])

{'mentor': 'jwalitha', 1: 'uma', 2: 'anu', 3: 'rohini'}
dict_keys(['mentor', 1, 2, 3])
dict_values(['jwalitha', 'uma', 'anu', 'rohini'])
uma


In [ ]:
d={"dept":"CSE","details":{"year":2,"sec":"D","strength":71}}
print("section: ",d["details"]["sec"])
print("year is: ",d["details"]["year"])
print("strength is:",d["details"]["strength"])

section:  D
year is:  2
strength is: 71


In [ ]:
#zip
l=["rohini",'r',1,6]
l2=["leela",8,"hi",5]
new=(zip(l,l2))
for i in new:
  print(i)

('rohini', 'leela')
('r', 8)
(1, 'hi')
(6, 5)


In [ ]:
#zip
l=["rohini",'r',1,6]
l2=["leela",8,"hi",5]
new=dict(zip(l,l2))
print(new)

{'rohini': 'leela', 'r': 8, 1: 'hi', 6: 5}


In [ ]:
#numpy
import numpy as np
a=np.array([1,2,3,4]) #1d array
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4]
1
(4,)


In [ ]:
#2d array
b=np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9],[7,8,9,3]])
print(b)#elements in each row is column
print(b.ndim)
print(b.shape)

[[1 2 3 4]
 [2 3 4 5]
 [6 7 8 9]
 [7 8 9 3]]
2
(4, 4)


In [ ]:
#3d array
c=np.array([[[1,2,3,4],[1,3,5,7],[5,4,3,2]],[[3,4,5,6],[2,6,2,5],[4,5,6,7]]])
print(c)
print(c.ndim)
print(c.shape)

[[[1 2 3 4]
  [1 3 5 7]
  [5 4 3 2]]

 [[3 4 5 6]
  [2 6 2 5]
  [4 5 6 7]]]
3
(2, 3, 4)


In [ ]:
a=np.ones((2,4,3))#2groups,2rows,3columns
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
a=np.zeros((2,4,3))#2groups,2rows,3columns
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
a=np.twos((2,4,3))#2groups,2rows,3columns
print(a)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.arange(1,10,2)#start,stop,step
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all numbers that  are divisible by 8 using arange function b/w 1 and 1000
a=np.arange(8,1001,8)
print(a)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#splitting a range into n numbers with common differnces
a=np.linspace(45,60,10)
print(a)

[45.         46.66666667 48.33333333 50.         51.66666667 53.33333333
 55.         56.66666667 58.33333333 60.        ]


In [ ]:
#study tuple and sets,documentation,qr code tasks